[build]
  command = "pnpm install && pnpm run build"
  functions = "netlify/functions"  # Path to your functions directory
  publish = "dist"  # Path to your static files (if any)

[dev]
  command = "pnpm dev"
  port = 8080

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
