import type { IAuthTokensRepository } from "src/interfaces/IAuthTokensRepository";
import type { IUserRepository } from "src/interfaces/IUserRepository";
import type { IMailNotifier } from "src/notifications/services/IMailNotifier";
import type { ISmsNotifier } from "src/notifications/services/ISmsNotifier";
import type { IOtpRepository } from "src/otp/otpRepository";
import type { IPasswordResetRepository } from "src/passwordReset/passwordReset.repository";
import type { IFacilityTypesRepository } from "src/rest-api/facilityTypes/facilityTypesRepository";
import type { IFeedbackRepository } from "src/rest-api/feedbacks/FeedbackRepository";
import type { IReceivedFeedbackRepository } from "src/rest-api/feedbacks/ReceivedFeedbackRepository";
import type { ILanguageRepository } from "src/rest-api/languages/LanguageRepository";
import type { IMedicalConditionsRepository } from "src/rest-api/medicalConditions/MedicalConditionsRepository";
import type { IMedicalDepartmentsRepository } from "src/rest-api/medicalDepartments/MedicalDepartmentsRepository";
import type { IMedicalFacilityRepository } from "src/rest-api/medicalFacility/medicalFacility.repository";
import type { IMedicalProceduresRepository } from "src/rest-api/medicalProcedures/MedicalProceduresRepository";
import type { IMedicalSpecialtiesRepository } from "src/rest-api/medicalSpecialties/MedicalSpecialtiesRepository";
import type { IPatientVisitorResourceCategoriesRepository } from "src/rest-api/patientVisitorResource/PatientVisitorResourceCategoriesRepository";
import type { IPatientVisitorResourceRepository } from "src/rest-api/patientVisitorResource/PatientVisitorResourceRepository";
import type { IPhysicianRepository } from "src/rest-api/physician/physician.repository";
import type { IReviewsRepository } from "src/rest-api/reviews/IReviewsRepository";

export type AppCtx = {
	readonly userRepository: IUserRepository;
	readonly authTokensRepository: IAuthTokensRepository;
	readonly otpRepository: IOtpRepository;
	readonly mailNotifier: IMailNotifier;
	readonly smsNotifier: ISmsNotifier;
	readonly medicalDepartmentsRepository: IMedicalDepartmentsRepository;
	readonly medicalSpecialtiesRepository: IMedicalSpecialtiesRepository;
	readonly medicalProceduresRepository: IMedicalProceduresRepository;
	readonly physicianFeedbackRepository: IFeedbackRepository;
	readonly medicalConditionsRepository: IMedicalConditionsRepository;
	readonly physicianRepository: IPhysicianRepository;
	readonly physicianReceivedFeedbackRepository: IReceivedFeedbackRepository;
	readonly languagesRepository: ILanguageRepository;
	readonly physicianReviewsRepository: IReviewsRepository;
	readonly passwordResetRepository: IPasswordResetRepository;
	readonly patientVisitorResourceCategoriesRepository: IPatientVisitorResourceCategoriesRepository;
	readonly facilityTypeRepository: IFacilityTypesRepository;
	readonly facilityReceivedFeedbackRepository: IReceivedFeedbackRepository;
	readonly facilityFeedbackRepository: IFeedbackRepository;
	readonly facilityReviewsRepository: IReviewsRepository;
	readonly patientVisitorResourceRepository: IPatientVisitorResourceRepository;
	readonly medicalFacilityRepository: IMedicalFacilityRepository;
};
