export const APP_ERR_CODES = {
	UNKNOWN: "UNKNOWN_ERROR",
	SERVER: "SERVER_ERROR",
	BAD_REQUEST: "BAD_REQUEST",
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	EMPTY_REQUEST_BODY: "EMPTY_REQUEST_BODY",
	INVALID_CONTENT_TYPE: "INVALID_CONTENT_TYPE",
	EXTERNAL: "EXTERNAL",
	FORBIDDEN: "FORBIDDEN",
	UNAUTHENTICATED: "UNAUTHENTICATED", // when a request doesn't have the right auth credentials
	VALIDATION: "VALIDATION",
	ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
	ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
	SIGNUP_FAILED: "SIGNUP_FAILED",
	ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
	INVALID_PAT: "INVALID_PAT", // invalid personal access token
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	UNVERIFIED_EMAIL_OR_PHONE: "UNVERIFIED_EMAIL_OR_PHONE",
	UNVERIFIED_EMAIL_AND_PHONE: "UNVERIFIED_EMAIL_AND_PHONE",
	EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
	PHONE_NUMBER_ALREADY_VERIFIED: "PHONE_NUMBER_ALREADY_VERIFIED",
} as const;

type ObjectValues<T> = T[keyof T];
export type AppErrCode = ObjectValues<typeof APP_ERR_CODES>;
